name: Test Installation

on:
  push:
    branches: [ "pu" ]
  pull_request:
    branches: [ "pu" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        perl-version: ['5.18', '5.26', '5.32', '5.40']

    runs-on: ${{ matrix.os }}
    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Configure Dependencies
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          tests: false
          install: Module::Build::Tiny

      - name: Install Path::Tiny (it fails on windows)
        uses: perl-actions/install-with-cpanm@v1.7
        if: runner.os == 'Windows'
        with:
          tests: false
          install: Path::Tiny

      - name: Build and Test
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          install: .
          tests: true
          verbose: true
